### ISSUE TITLE
phantom.js error

### ISSUE THREAD

**Issue by nasum** [tmtk75/aws-cloudwatch-chart-slack#1]
This product is perfect for my product.
but, error occured...

It was excuted Slack.

```
my_product cloudwatch i-xxxxxxxx
```

```
 [Fri Aug 26 2016 19:32:50 GMT+0900 (JST)] ERROR Error: spawn /home/hubot/my_product/node_modules/aws-cloudwatch-chart-slack/node_modules/.bin/phantomjs ENOENT
at exports._errnoException (util.js:1012:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
at onErrorNT (internal/child_process.js:348:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

please help me....

**Comment by tmtk75** [comment]
OMG, I've not noticed issues are created. Sorry for late reply.

I've updated version of phantomjs at d6742b4693e2fa7d9b5151c8dc26bbcb0eb37220, how about this?

**Comment by tmtk75** [comment]
I'll close because of getting stale.
